### ISSUE TITLE
Trailing whitespace in line 1 of train.csv and test.csv

### ISSUE THREAD

**Issue by jakpra** [german-easy-to-read/statements#1]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

This leads to the last pandas df key being called 'statement_spans ' rather than 'statement_spans'

### How to reproduce the bug

```
import pandas as pd
train_df = pd.read_csv ('data/train.csv')
train_df.keys()[-1]
```
'statement_spans '

### Error messages and logs

```
The error message you got, with the full traceback if available. Please paste it between these triple backticks.
```

### What operating system are you using?

Windows

### Where are you seeing the problem on?

Running locally without Docker

**Comment by MiriUll** [comment]
Hi, thanks a lot for pointing this out. I have removed the whitespaces from the data.
