### ISSUE TITLE
Repeated whitespaces lead to empty tokens

### ISSUE THREAD

**Issue by jakpra** [german-easy-to-read/statements#2]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Around \newline tokens there sometimes are repeated whitespaces in the phrase text, which a naive whitespace tokenizer turns into empty tokens.

### How to reproduce the bug

This seems to be exactly what happened here, e.g. token 3 in the trial.csv example and token 12 in the train.csv example.
Would it be possible to remove any whitespace clusters and resulting empty tokens from the official data at this point?
I guess it shouldn't be a big issue even if they stay, as we can just work with the provided tokenization, but it seems a bit brittle...

trial.csv
`38789,repair-cafe,"Sie treffen sich,  \newline um gemeinsam kaputte Dinge zu reparieren.",1_short,Umwelt|Entsorgung,2013-08-06T10:39:17Z,eaab3232dd7a824a6a774fd2f2814e47,"0:=Sie 1:=treffen 2:=sich, 3:= 4:=\newline 5:=um 6:=gemeinsam 7:=kaputte 8:=Dinge 9:=zu 10:=reparieren.",3,"[[0,1,2],[7,8,9,10],[6]]",infinitive`

train.csv
`1010,aldous-huxley,"Er stirbt am 22. November 1963. \newline In Los Angeles, USA. \newline  \newline Im Jahr 1932: \newline Huxley schreibt seinen berühmtesten Roman.",3_long,Personen|Seiten_mit_defekten_Dateilinks,2022-01-31T17:31:47Z,e800bebc9060331edfac65e663a55570,"0:=Er 1:=stirbt 2:=am 3:=22. 4:=November 5:=1963. 6:=\newline 7:=In 8:=Los 9:=Angeles, 10:=USA. 11:=\newline 12:= 13:=\newline 14:=Im 15:=Jahr 16:=1932: 17:=\newline 18:=Huxley 19:=schreibt 20:=seinen 21:=berühmtesten 22:=Roman.",0,`

### Error messages and logs

```
The error message you got, with the full traceback if available. Please paste it between these triple backticks.
```

### What operating system are you using?

Windows

### Where are you seeing the problem on?

Running locally without Docker

**Comment by MiriUll** [comment]
The data from the Hurraki homepage is quite noisy. We decided to keep the noise to reflect upon noisy real-world data. Yet, these empty tokens are not annotated in the statement spans. So, you can, of course, remove them in your (pre-)processing.
