### ISSUE TITLE
Test set with labels

### ISSUE THREAD

**Issue by jakpra** [german-easy-to-read/statements#3]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Is it intended that the test.csv dataset already contains gold labels? I'm assuming this is a development/validation set then and you have kept another split with secret labels for the official evaluation?

### How to reproduce the bug

n/a

### Error messages and logs

```
The error message you got, with the full traceback if available. Please paste it between these triple backticks.
```

### What operating system are you using?

Not applicable (e.g. you're using GitHub Pages or other hosting)

### Where are you seeing the problem on?

Deployed site

**Comment by MiriUll** [comment]
Yes, this dataset is only for benchmarking the submitted systems during the validation/test phase. We have another unpublished dataset for the final scoring where we won't release the labels until the end of the evaluation phase.
