### ISSUE TITLE
Span definitions with invalid token IDs in training data

### ISSUE THREAD

**Issue by saeub** [german-easy-to-read/statements#4]
Three samples in `train.csv` have out-of-bounds token IDs in their span definitions:

**sent-id 12174:** `0:=Anemonen-fische 1:=leben 2:=meistens 3:=als 4:=Paar 5:=in 6:=einer 7:=Anemone.,2,"[[3, 4], [6, 8]]"`
→ Should probably be `[[3, 4], [5, 7]]`?

**sent-id 27038:** `0:=Kosmopolitismus 1:= 2:=ist 3:=wenn 4:=man 5:=die 6:=ganze 7:=Welt 8:=als 9:=Heimat 10:=hat.,2,"[[0, 2], [3, 4, 6, 78, 9, 10]]"`
→ Should probably be `[[0, 2], [3, 4, 6, 7, 8, 9, 10]]`?

**sent-id 42013:** `0:=Einer 1:=(1) 2:=alleine 3:=spielt 4:=gegen 5:=mehrere.,2,"[[0, 2, 3, 4, 5, 6], [1]]"`
→ Should probably be `[[0, 2, 3, 4, 5], [1]]`?

**Comment by MiriUll** [comment]
Hi,
thank you very much for pointing this out! We have corrected the samples in the training data and added an automated check so that this won't happen again in the evaluation data.
